### ISSUE TITLE
Plugin lags with larger config files

### ISSUE THREAD

**Issue by riesegarder** [1Axen/blink#12]
Lag spikes occur mostly when adding/removing new lines, and also when autocomplete is triggered
https://jmp.sh/lgfvAHF9

For reference, the config I'm editing is 191 lines with 4,350 characters in total 

I've been noticing the lag gradually, it's just that I ignored them and assumed it's my potato laptop, but it's gotten to this point where I actually make changes on Notepad instead and only use the plugin to generate the network modules..

If there's a way to disable the autocomplete (or whatever was causing the lag), I'd be fine with just having the editor even without the colors

**Comment by 1Axen** [comment]
The Studio Plugin would benefit from some refactoring in a lot areas, I've got a few ideas to better optimise the plugin. As for the time being I will look into adding the ability to disable some editor features to help with the lag.

**Comment by 1Axen** [comment]
I've just merged #13 and released [v0.13.5](https://github.com/1Axen/blink/releases/tag/v0.13.5) containing some performance improvements to the plugin, it's nothing major but it should help with the performance issues. Give it a try and let me know how it goes!

I will be keeping the issue open as I have more changes in mind and I am not yet satisfied with the performance of the studio plugins, said changes are more than a weekends worth of work though as they require refactoring of the parser.

**Comment by riesegarder** [comment]
Just checked it out -- unfortunately still the same for me 😓 just tried it using the same files I got and get the same performance issues as before.

**Comment by riesegarder** [comment]
I wanna update a bit: I've got a PC now with much better perf than the laptop I used to work on, but the plugin lag is still the same :( was half expecting it'd be better here but somehow there's barely any difference

**Comment by 1Axen** [comment]
I'm currently working on a complete rewrite of blink which will massively improve the performance of the editor, for reference the new lexer is 2.4x faster on the same file (2.35ms to 974 microseconds). Unfortunately this means that outside of major bug fixes I'm not maintaining the current version.
